[functions.registrar-interesse]
verify_jwt = false

[functions.abrir-cartilha]
verify_jwt = false

[functions.login-with-cim]
verify_jwt = false

[functions.ativar-conta]
verify_jwt = true

[functions.recuperar-senha-cim]
verify_jwt = false

[functions.gerenciar-irmao]
verify_jwt = true

[functions.bootstrap-convite-admin]
verify_jwt = false
